### PR TITLE
Bug: Don't apply `exports` to relative local imports.

### LINKED ISSUE #70: Bug: Cannot find export error for glob exports
Hi, i'm using this lib as a part of serverless-jetpack and just briefly looked in the code so i'm not sure if this is the correct place to raise my concern. 

The problem i'm running into: 
`Error: Cannot find export './middleware.js.mjs' in module './middleware.js' from './node_modules/graphql-middleware/dist'.`

The library responsible for this error is graphql-middleware. The exports in the package.json looks like this:
```json
"exports": {
  "./*": {
    "require": "./*.js",
    "import": "./*.mjs"
  },
}
```

The files located in the dist dir of graphql-middleware are actually just called `middleware.mjs`. 
As far as i can see the resolve.exports lib returns the wrong relative paths. But im not sure if some configuration mistake on my side is the problem or if this isn't working properly.

### PR DESCRIPTION
**Pull request by ryan-roemer**
Do not apply `package.json:exports` resolution to relative local file imports. Fixes #70

### CODE REVIEW

File: lib/trace.js [hunk 1]
```diff
@@ -52,10 +52,6 @@ const CONDITIONS = [
 const PASSTHROUGH_EXPORTS = {
   "./": new Set([
     "./"
-  ]),
-  "./*": new Set([
```
Comment (ryan-roemer) [inline lib/trace.js:56]: Turns out this was the same bug and this was not the appropriate solution.

File: lib/trace.js [hunk 2]
```diff
@@ -262,42 +268,43 @@ const _resolveDep = async ({
...
+        // > by creating an export for the root of the package "./*": "./*".
+        // > This exposes every file in the package at the cost of disabling
+        // > the encapsulation and potential tooling benefits this provides.
+        // > As the ES Module loader in Node.js enforces the use of the full
+        // > specifier path, exporting the root rather than being explicit
+        // > about entry is less expressive than either of the prior examples.
+        // > Not only is encapsulation lost but module consumers are unable to
+        // > import feature from 'my-mod/feature' as they need to provide the
+        // > full path import feature from 'my-mod/feature/index.js.
+        Object.entries(PASSTHROUGH_EXPORTS).forEach(([key, vals]) => {
```
Comment (ryan-roemer) [inline lib/trace.js:295]: This should have originally been down before looping on CONDITIONS and not repeatedly in CONDITIONS.

**Comment by ryan-roemer** [comment]
Released in `trace-deps@0.4.4`.
